config/routes.rb
Dashboard::Application.routes.draw do
  resources :recruiters

  

end

app/models/recruiter.rb
class Recruiter < ActiveRecord::Base
end

app/models/team.rb
class Team < ActiveRecord::Base
  has_many :recruiters
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/recruiters_controller.rb
class RecruitersController < ApplicationController
  before_action :set_recruiter, only: [:show, :edit, :update, :destroy]

  # GET /recruiters
  # GET /recruiters.json
  def index
    @recruiters = Recruiter.all
  end

  # GET /recruiters/1
  # GET /recruiters/1.json
  def show
  end

  # GET /recruiters/new
  def new
    @recruiter = Recruiter.new
  end

  # GET /recruiters/1/edit
  def edit
  end

  # POST /recruiters
  # POST /recruiters.json
  def create
    @recruiter = Recruiter.new(recruiter_params)

    respond_to do |format|
      if @recruiter.save
        format.html { redirect_to @recruiter, notice: 'Recruiter was successfully created.' }
        format.json { render action: 'show', status: :created, location: @recruiter }
      else
        format.html { render action: 'new' }
        format.json { render json: @recruiter.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /recruiters/1
  # PATCH/PUT /recruiters/1.json
  def update
    respond_to do |format|
      if @recruiter.update(recruiter_params)
        format.html { redirect_to @recruiter, notice: 'Recruiter was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @recruiter.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recruiters/1
  # DELETE /recruiters/1.json
  def destroy
    @recruiter.destroy
    respond_to do |format|
      format.html { redirect_to recruiters_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_recruiter
      @recruiter = Recruiter.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def recruiter_params
      params.require(:recruiter).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/recruiters_helper.rb
module RecruitersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Dashboard</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/recruiters/_form.html.erb
<%= form_for(@recruiter) do |f| %>
  <% if @recruiter.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@recruiter.errors.count, "error") %> prohibited this recruiter from being saved:</h2>

      <ul>
      <% @recruiter.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/recruiters/edit.html.erb
<h1>Editing recruiter</h1>

<%= render 'form' %>

<%= link_to 'Show', @recruiter %> |
<%= link_to 'Back', recruiters_path %>

app/views/recruiters/index.html.erb
<h1>Listing recruiters</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @recruiters.each do |recruiter| %>
      <tr>
        <td><%= recruiter.name %></td>
        <td><%= link_to 'Show', recruiter %></td>
        <td><%= link_to 'Edit', edit_recruiter_path(recruiter) %></td>
        <td><%= link_to 'Destroy', recruiter, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Recruiter', new_recruiter_path %>

app/views/recruiters/new.html.erb
<h1>New recruiter</h1>

<%= render 'form' %>

<%= link_to 'Back', recruiters_path %>

app/views/recruiters/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @recruiter.name %>
</p>

<%= link_to 'Edit', edit_recruiter_path(@recruiter) %> |
<%= link_to 'Back', recruiters_path %>